config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :movies do
    member do
      post :join
      post :quit
    end
    resources :reviews
  end

  namespace :account do
    resources :movies
  end

  namespace :admin do
    resources :movies 
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :reviews
  belongs_to :user

  has_many :movie_favorites
  has_many :members, through: :movie_favorites, source: :user

  validates :title, :image, :actor, :director,  presence: true
end

app/models/movie_favorite.rb
class MovieFavorite < ApplicationRecord
  belongs_to :movie
  belongs_to :user 
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :movies

  has_many :movie_favorites
  has_many :love_movies, through: :movie_favorites, source: :movie

  def is_member_of?(movie)
    love_movies.include?(movie)
  end

  def join!(movie)
    love_movies << movie
  end

  def quit!(movie)
    love_movies.delete(movie)
  end

  def admin?
    is_admin
  end
end

app/controllers/account/movies_controller.rb
class Account::MoviesController < ApplicationController

  def index
    @movies = current_user.love_movies.all 
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  before_action :admin_required 

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      current_user.join!(@movie)
      redirect_to admin_movies_path
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = Review.all
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to admin_movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to admin_movies_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :picture, :description, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def admin_required
    if !current_user.admin?
      redirect_to "/"
    end 
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:join]

  def index
    @movies = Movie.all
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.user = current_user
    if @movie.save
      current_user.join!(@movie)
      redirect_to movies_path
    else
      render :new
    end
  end

  def show
    @movie = Movie.find(params[:id])
    @reviews = @movie.reviews 
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end

  def join
    @movie = Movie.find(params[:id])

    if !current_user.is_member_of?(@movie)
      current_user.join!(@movie)
      flash[:notice] = "加入收藏"
    else
      flash[:notice] = "无法加入收藏"
    end
    redirect_to movie_path(@movie)
  end

  def quit
    @movie = Movie.find(params[:id])
    if current_user.is_member_of?(@movie)
      current_user.quit!(@movie)
      flash[:warning] = "取消收藏"
    else
      flash[:warning] = "无法取消收藏"
    end
    redirect_to movie_path(@movie)
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :picture, :description, :image,
                                   :director, :actor, :movie_type, :country, :language, :show_time, :film_length)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:new]
  def new
    @movie = Movie.find(params[:movie_id])
    if current_user.is_member_of?(@movie)
      @review = Review.new
    else
      redirect_to :back
      flash[:warning] = "please join this movie"
    end
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user
    if @review.save
      redirect_to movie_path(@movie)
    else
      render :new
    end
  end

  private
  def review_params
    params.require(:review).permit(:comment)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "welcome"
  end
end

app/helpers/account/movies_helper.rb
module Account::MoviesHelper
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze

  def flashes_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "notice", "alert", "warning"
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/movies/index.html.erb
<table class="table">
  <thead>
    <th>#</th>
    <th>title</th>
    <th>picture</th>
    <th>option</th>
  </thead>
  <tbody>
    <% @movies.each do |movie|%>
      <tr>
        <th><%= movie.id%></th>
        <th>
          <% if movie.image.present? %>
            <%= image_tag(movie.image.thumb.url, class: "thumbnail")%>
         <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
          <% end %>
        </th>
        <th><%= movie.title%></th>
        <th>
          <%= link_to("edit", edit_admin_movie_path(movie), class: "btn btn-default")%>
          <%= link_to("delete", admin_movie_path(movie), method: :delete, class: "btn btn-default")%>
        </th>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/common/_flashes.html.erb
<% if flash.any?%>
  <% user_facing_flashes.each do |key, value|%>
    <div class="alert alert-dismissable alert-<%= flashes_class(key)%>">
      <button class="close" data-dismiss="alert">x</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container-fluid text-center" style="margin-top: 100px;">
  <p>
    Copyright © Rails101 <br>
    Design by xxx 
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="/" class="navbar-brand">rails101</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collspse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if !current_user%>
           <li><%= link_to("signup", new_user_registration_path)%></li>
           <li><%= link_to("lonin", new_user_session_path)%></li>
        <% else %>
          <li  class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.email%>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin?%>
                <li><%= link_to("admin", admin_movies_path)%></li>
              <% end %>
              <li><%= link_to("favorite", account_movies_path)%></li>
              <li><%= link_to("logout", destroy_user_session_path, method: :delete)%></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails102</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "common/navbar"%>
      <%= render "common/flashes"%>
      <%= yield %>
    </div>
    <%= render "common/footer"%>
  </body>
</html>

app/views/movies/edit.html.erb
<h1>edit movie</h1>
<div class="container">
  <%= simple_form_for @movie do |f|%>
    <%= f.input :title%>
    <%= f.input :description%>
    <% if @movie.image.present?%>
      <%= image_tag(@movie.image.thumb.url)%>
    <% end %>
    <%= f.input :image, as: :file%>
    <%= f.submit "submit",data: { dimiss_with: "submitting..."}%>
  <% end %>
</div>

app/views/movies/index.html.erb
<div class="row row-backgroud">
<div class="container">
  <h1 class="text-center">movie comment</h1>
    <p class="text-right",style="margin:15px;"><%= link_to("add new movie", new_movie_path(@movie), class: "btn btn-default")%></p>
    <hr>
  <div class="row">
    <% @movies.each do |movie|%>
      <div class="col-xs-6 col-md-3">
        <div class="movie-index-show">
        <%= link_to movie_path(movie) do %>
          <% if movie.image.present?%>
            <%= image_tag(movie.image.thumb.url, class: "thumbnail")%>
          <% else %>
            <%= image_tag("http://placehold.it/200x200&text=No Pic", class: "thumbnail")%>
          <% end %>
        <% end %>
      </div>
        <p class="text-center"><%= movie.title%></p>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/movies/new.html.erb
<h1>new movie</h1>
<div class="container">
  <%= simple_form_for @movie do |f|%>
    <%= f.input :title%>
    <%= f.input :director%>
    <%= f.input :actor%>
    <%= f.input :movie_type%>
    <%= f.input :country, collection:["中国","美国","英国","日本","韩国"] %>
    <%= f.input :language, collection: ["英语","中文","日文"]%>
    <div class="movie-time">
      <%= f.input :show_time, :as => :string%>
    </div>
    <%= f.input :film_length%>
    <%= f.input :description%>
    <%= f.input :image, as: :file%>
    <%= f.submit "submit",data: { dimiss_with: "submitting..."}%>
  <% end %>
</div>

<script>
    $(".movie-time").datepicker({format: "yyyy/mm/dd"});
</script>

app/views/movies/show.html.erb
<div class="row row-backgroud">
<h1 class="text-center"><%= @movie.title%></h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="movie-show">
      <% if @movie.image.present?%>
        <%= image_tag(@movie.image.medium.url, class: "thumbnail")%>
      <% else %>
        <%= image_tag("http://placehold.it/400x400&text=No Pic", class: "thumbnail") %>
      <% end %>
      <span class="pull-center">
        <% if current_user && current_user.is_member_of?(@movie)%>
          <label class="label label-success">favorite</label>
          <%= link_to  quit_movie_path(@movie), method: :post, class: "btn btn-default", style: "color: red;" do %>
          <i class="fa fa-heart" aria-hidden="true"></i>
          <% end %>
        <% else %>
            <label class="label label-warning">点击收藏</label>
            <%= link_to  join_movie_path(@movie), method: :post, class: "btn btn-default" do %>
            <i class="fa fa-heart-o" aria-hidden="true"></i>
            <% end %>
        <% end %>
      </span>
      </div>
    </div>
    <div class="col-md-6">
      <div class="movie-description">
      <p style="margin-top:30px;">导演：    <%= @movie.director%></p>
      <p>主演：    <%= @movie.actor%></p>
      <p>类型：    <%= @movie.movie_type%></p>
      <p>国家：    <%= @movie.country%></p>
      <p>语言：    <%= @movie.language%></p>
      <p>上映时间： <%= @movie.show_time%></p>
      <p>片长：    <%= @movie.film_length%></p>
      <p>剧情介绍： <%= simple_format(@movie.description)%></p>
      </div>
    </div>
  </div>

</div>

<div class="container">
<div class="pull-left" style="margin: 15px;">
  <%# if current_user.is_member_of?(@movie)%>
    <%= link_to("write comment", new_movie_review_path(@movie), class: "btn btn-default")%>
  <%# else %>
    <%#= flash[:noice] = "please join this movie"%>
    <%# end %>
</div>
<div class="comment-show">
<table class="table">
  <% @reviews.each do |review|%>
  <tr>
  <td>
    <%= review.user.email %>
  </td>
  <td>
    <%= review.comment%>
  </td>
    </tr>
  <% end %>
</table>
</div>
</div>
</div>

app/views/reviews/new.html.erb
<div class="container">
  <%= simple_form_for [@movie, @review] do |f|%>
    <%= f.input :comment%>
    <%= f.submit "submit",data: {disable_with: "submitting..."}%>
  <% end %>
</div>

app/views/welcome/index.html.erb
<h1>welcome</h1>